name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Download MSYS2
        run: |
          Invoke-WebRequest -Uri https://mirror.msys2.org/distrib/x86_64/msys2-base-x86_64-20240120.tar.xz -OutFile msys2.tar.xz
          7z x msys2.tar.xz -so | 7z x -aoa -si -ttar -o"$env:GITHUB_WORKSPACE\msys64"
          echo "$env:GITHUB_WORKSPACE\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "$env:GITHUB_WORKSPACE\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install pkgconf
        run: |
          Invoke-WebRequest -Uri https://github.com/pkgconf/pkgconf/releases/download/pkgconf-2.1.0/pkgconf-2.1.0-win64.zip -OutFile pkgconf.zip
          Expand-Archive pkgconf.zip -DestinationPath "$env:GITHUB_WORKSPACE\pkgconf"
          echo "$env:GITHUB_WORKSPACE\pkgconf" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Prepare autogen.input
        run: |
          echo '--with-external-tar="$env:GITHUB_WORKSPACE/ext_sources"' > autogen.input
          echo '--enable-release-build' >> autogen.input
          echo '--with-lang=en-US' >> autogen.input
          echo '--disable-dependency-tracking' >> autogen.input
          echo "PKG_CONFIG=$env:GITHUB_WORKSPACE\\pkgconf\\pkgconf.exe" >> autogen.input

      - name: Run autogen.sh inside MSYS2
        shell: msys2 {0}
        run: |
          cd $GITHUB_WORKSPACE
          ./autogen.sh

      - name: Build LibreOffice (Tellesoft Office)
        shell: msys2 {0}
        run: |
          cd $GITHUB_WORKSPACE
          make

      - name: Package Installer (MSI)
        shell: msys2 {0}
        run: |
          cd $GITHUB_WORKSPACE
          make MSIINSTALLERPRODUCTNAME=TellesoftOffice msi

      - name: Upload TellesoftOffice.msi
        uses: actions/upload-artifact@v4
        with:
          name: TellesoftOfficeInstaller
          path: '**/TellesoftOffice.msi'
