      - name: Install Cygwin for bash
        uses: cygwin/cygwin-install-action@v4
        with:
          packages: >-
            bash
            unzip
            zip
            tar
            bison
            flex
            autoconf
            automake
            m4
            pkg-config
            dos2unix

      - name: Force /bin/sh to bash (remove and re-link)
        run: |
          C:\cygwin\bin\bash.exe -lc "cd /bin && rm -f sh && ln -s bash sh && ls -l sh"
        shell: cmd

      - name: Convert all *.sh scripts to Unix (LF) format
        run: |
          C:\cygwin\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && find . -type f -name '*.sh' -exec dos2unix {} \;"
        shell: cmd
