name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: true
        install: >-
          base-devel
          git
          make
          autoconf
          automake
          libtool
          pkgconf
          perl
          sed
          grep

    - name: Set PATH to MSBuild (already preinstalled)
      run: echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Prepare autogen.input
      run: echo "--disable-firebird-sdbc" > autogen.input

    - name: Run autogen.sh
      shell: msys2 {0}
      run: ./autogen.sh

    - name: Build Tellesoft Office
      shell: msys2 {0}
      run: make

    - name: Package MSI Installer
      shell: msys2 {0}
      run: make msinstaller MSI_NAME=TellesoftOffice.msi

    - name: Upload TellesoftOffice.msi
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOfficeInstaller
        path: instdir/TellesoftOffice.msi
