name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Locate VsDevCmd.bat path
      id: vsdevcmd
      shell: powershell
      run: |
        $vsPath = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" `
          -latest -products * -requires Microsoft.Component.MSBuild `
          -find "Common7\Tools\VsDevCmd.bat"
        echo "Found: $vsPath"
        echo "VSDEVCMD=$vsPath" >> $env:GITHUB_ENV

    - name: Install MSYS2
      shell: cmd
      run: |
        curl -L -o msys2.exe https://github.com/msys2/msys2-installer/releases/download/2023-05-26/msys2-x86_64-20230526.exe
        msys2.exe install --root C:\_msys2 --confirm-command

    - name: Update MSYS2 and install dependencies
      shell: cmd
      run: |
        C:\_msys2\usr\bin\bash.exe -lc "pacman -Syuu --noconfirm"
        C:\_msys2\usr\bin\bash.exe -lc "pacman -S --noconfirm base-devel git autoconf automake libtool pkgconf mingw-w64-x86_64-toolchain"

    - name: Prepare autogen.input
      shell: bash
      run: echo "PKG_CONFIG=/usr/bin/pkgconf" > autogen.input

    - name: Run autogen.sh using MSYS2 + Visual Studio
      shell: cmd
      run: |
        call "%VSDEVCMD%" && ^
        for /f "delims=" %%i in ('C:\_msys2\usr\bin\bash.exe -lc "cygpath -u '%GITHUB_WORKSPACE%'"') do set "WORKSPACE=%%i" && ^
        C:\_msys2\usr\bin\bash.exe -lc "cd $WORKSPACE && ./autogen.sh"

    - name: Build Tellesoft Office
      shell: cmd
      run: |
        call "%VSDEVCMD%" && ^
        for /f "delims=" %%i in ('C:\_msys2\usr\bin\bash.exe -lc "cygpath -u '%GITHUB_WORKSPACE%'"') do set "WORKSPACE=%%i" && ^
        C:\_msys2\usr\bin\bash.exe -lc "cd $WORKSPACE && make -j$(nproc)"

    - name: Generate MSI installer
      shell: cmd
      run: |
        C:\_msys2\usr\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && make install"

    - name: Upload TellesoftOffice.msi
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOffice.msi
        path: '**/TellesoftOffice.msi'
