name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install MSYS2 and required packages
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >
          base-devel
          autoconf
          automake
          make
          pkg-config
          git
          zip
          unzip
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-toolchain

    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Run autogen.sh
      shell: msys2 {0}
      run: |
        ./autogen.sh \
          --with-theme=colibre \
          --disable-firebird-sdbc \
          --disable-ccache \
          --enable-release-build=yes \
          --with-java \
          --with-package-format=msi \
          --host=x86_64-w64-mingw32 \
          --build=x86_64-pc-linux-gnu \
          --srcdir=$(pwd) \
          --enable-option-checking=fatal

    - name: Build LibreOffice (Tellesoft Office)
      shell: msys2 {0}
      run: |
        make -j$(nproc)

    - name: Generate MSI installer
      shell: msys2 {0}
      run: |
        make installer

    - name: Upload TellesoftOffice.msi
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOffice.msi
        path: instdir/install/en-US/Tellesoft
