name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install Chocolatey packages
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        choco install -y winflexbison3 nasm

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          autoconf
          automake
          libtool
          m4
          gettext
          pkgconf
          make

    - name: Set up MSVC environment file
      run: echo call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" > vsenv.bat

    - name: Run autogen.sh using MSYS2 + MSVC
      shell: msys2 {0}
      run: |
        ./vsenv.bat
        ./autogen.sh

    - name: Build Tellesoft Office
      shell: msys2 {0}
      run: |
        ./vsenv.bat
        make -j$(nproc)

    - name: Generate MSI installer
      shell: msys2 {0}
      run: |
        ./vsenv.bat
        make msi

    - name: Upload TellesoftOffice.msi
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOffice
        path: instdir/TellesoftOffice.msi
