name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install Cygwin with required packages
      uses: cygwin/cygwin-install-action@v4
      with:
        packages: >-
          git make gcc-core gcc-g++ perl python3 autoconf automake
          libtool gettext pkg-config m4 unzip zip tar bison flex
          dos2unix

    - name: Prepare autogen.input
      run: echo 'PKG_CONFIG=/usr/bin/pkgconf' > autogen.input
      shell: bash

    - name: Convert autogen.sh line endings
      run: |
        C:\cygwin\bin\bash.exe -lc "dos2unix $(cygpath -u '${{ github.workspace }}')/autogen.sh"
      shell: cmd

    - name: Run autogen.sh using Cygwin + Visual Studio
      run: |
        call "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && ^
        C:\cygwin\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && ./autogen.sh"
      shell: cmd

    - name: Build LibreOffice (Tellesoft Office)
      run: |
        call "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && ^
        C:\cygwin\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && make"
      shell: cmd

    - name: Create MSI Installer (instsetoo_native)
      run: |
        call "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && ^
        C:\cygwin\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && cd instsetoo_native && make"
      shell: cmd

    - name: Rename and move MSI
      run: |
        mkdir output
        for /R %%f in (*.msi) do (
          copy "%%f" "output\TellesoftOffice.msi"
          goto :done
        )
        :done
      shell: cmd

    - name: Upload MSI artifact
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOffice.msi
        path: output/TellesoftOffice.msi
