name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Cygwin and packages
        uses: cygwin/cygwin-install-action@v4
        with:
          packages: >
            gcc-core gcc-g++ make autoconf automake libtool
            git unzip zip bison flex pkg-config perl python3
            libxslt curl wget gnupg p7zip tar

      - name: Prepare autogen.input
        run: echo '--with-theme=colibre' > autogen.input

      - name: Run autogen.sh using Cygwin
        run: |
          C:\cygwin64\bin\bash -lc "cd \"$(cygpath -u '${{ github.workspace }}')\" && ./autogen.sh"

      - name: Build LibreOffice (Tellesoft Office)
        run: |
          C:\cygwin64\bin\bash -lc "cd \"$(cygpath -u '${{ github.workspace }}')\" && make"

      - name: Package Installer (MSI)
        run: |
          C:\cygwin64\bin\bash -lc "cd \"$(cygpath -u '${{ github.workspace }}')\" && make msinstaller"

      - name: Upload TellesoftOffice.msi
        uses: actions/upload-artifact@v4
        with:
          name: TellesoftOffice.msi
          path: |
            **/TellesoftOffice.msi
