name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Download and install MSYS2
      shell: cmd
      run: |
        curl -L -o msys2-installer.exe https://github.com/msys2/msys2-installer/releases/download/2023-05-26/msys2-x86_64-20230526.exe
        msys2-installer.exe install --root C:\_msys2 --confirm-command

    - name: Update MSYS2 and install build dependencies
      shell: cmd
      run: |
        C:\_msys2\usr\bin\bash.exe -lc "pacman -Syuu --noconfirm"
        C:\_msys2\usr\bin\bash.exe -lc "pacman -S --noconfirm base-devel git autoconf automake libtool pkgconf"

    - name: Convert path and run autogen.sh
      shell: cmd
      run: |
        setlocal enabledelayedexpansion
        for /f "delims=" %%i in ('C:\_msys2\usr\bin\bash.exe -lc "cygpath -u '%GITHUB_WORKSPACE%'"') do set "WORKSPACE=%%i"
        C:\_msys2\usr\bin\bash.exe -lc "cd $WORKSPACE && ./autogen.sh"

    - name: Build Tellesoft Office
      shell: cmd
      run: |
        setlocal enabledelayedexpansion
        for /f "delims=" %%i in ('C:\_msys2\usr\bin\bash.exe -lc "cygpath -u '%GITHUB_WORKSPACE%'"') do set "WORKSPACE=%%i"
        C:\_msys2\usr\bin\bash.exe -lc "cd $WORKSPACE && make -j$(nproc)"

    - name: Generate MSI installer
      shell: cmd
      run: |
        "C:\_msys2\usr\bin\bash.exe" -lc "cd $(cygpath -u '${{ github.workspace }}') && make install"

    - name: Upload TellesoftOffice.msi
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOffice.msi
        path: '**/TellesoftOffice.msi'
