name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Cygwin with required packages
        uses: cygwin/cygwin-install-action@v4
        with:
          packages: >-
            git make gcc-core gcc-g++ perl python3 autoconf automake
            libtool gettext pkg-config m4 unzip zip tar bison flex dos2unix

      - name: Add Cygwin to PATH
        run: echo "C:\cygwin\bin" >> $env:GITHUB_PATH

      - name: Prepare autogen.input
        run: echo '--with-theme=colibre' > autogen.input
        shell: bash

      - name: Convert line endings (fix CRLF issues)
        run: dos2unix $(find . -name 'autogen.sh')
        shell: bash

      - name: Install LibreOffice MSVC-compatible make
        shell: bash
        run: |
          wget -O /tmp/make-4.2.1-msvc.exe https://dev-www.libreoffice.org/bin/cygwin/make-4.2.1-msvc.exe
          mkdir -p /opt/lo/bin
          mv /tmp/make-4.2.1-msvc.exe /opt/lo/bin/make.exe
          cd /opt/lo/bin && cp make.exe make && chmod +x make
