name: Build Tellesoft Office (Windows MSI)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install Cygwin with required packages
      uses: cygwin/cygwin-install-action@v4
      with:
        packages: >-
          git make gcc-core gcc-g++ perl python3 autoconf automake
          libtool gettext pkg-config m4 unzip zip tar bison flex dos2unix

    - name: Prepare autogen.input
      shell: bash
      run: echo '--with-theme=colibre' > autogen.input

    - name: Convert autogen.sh line endings (fix \r issues)
      shell: cmd
      run: |
        C:\cygwin\bin\bash.exe -lc "dos2unix $(cygpath -u '${{ github.workspace }}')/autogen.sh"

    - name: Run autogen.sh using Cygwin + Visual Studio
      shell: cmd
      run: |
        call "%ProgramFiles%\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat" && ^
        C:\cygwin\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && ./autogen.sh"

    - name: Build LibreOffice (Tellesoft Office)
      shell: cmd
      run: |
        call "%ProgramFiles%\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat" && ^
        C:\cygwin\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && make build-nocheck"

    - name: Create MSI Installer (instsetoo_native)
      shell: cmd
      run: |
        call "%ProgramFiles%\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat" && ^
        C:\cygwin\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && make instsetoo_native"

    - name: Rename and move MSI
      shell: cmd
      run: |
        mkdir output
        for /R %%f in (*.msi) do (
          copy "%%f" "output\TellesoftOffice.msi"
          goto :done
        )
        :done

    - name: Upload MSI artifact
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOffice
        path: output/TellesoftOffice.msi
