name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up MSVC environment file
      run: |
        echo call "\"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat\"" > vsenv.bat
        type vsenv.bat

    - name: Run autogen.sh using MSYS2 + MSVC
      shell: msys2 {0}
      run: |
        ./vsenv.bat
        ./autogen.sh

    - name: Build Tellesoft Office
      shell: msys2 {0}
      run: |
        make

    - name: Generate MSI installer
      shell: msys2 {0}
      run: |
        make installer

    - name: Upload TellesoftOffice.msi
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOffice
        path: ./instsetoo_native/**/TellesoftOffice.msi
