name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Download and extract MSYS2 manually
      run: |
        curl -L -o msys2.tar.xz https://github.com/msys2/msys2-installer/releases/download/2024-05-22/msys2-base-x86_64-20240522.tar.xz
        mkdir msys2
        "C:\Program Files\Git\usr\bin\xz.exe" -d msys2.tar.xz
        tar -xvf msys2.tar -C msys2 --strip-components=1

    - name: Set up MSVC environment
      run: |
        echo "Setting up VS build environment..."
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" > vsenv.bat
        echo call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" > venv.bat
        echo bash.exe --login -c "./autogen.sh" >> venv.bat

    - name: Run autogen.sh using MSYS2 bash
      run: |
        cd msys2
        ./usr/bin/bash.exe --login -c "cd $GITHUB_WORKSPACE && ./autogen.sh"

    - name: Build Tellesoft Office
      run: |
        cd msys2
        ./usr/bin/bash.exe --login -c "cd $GITHUB_WORKSPACE && make"

    - name: Generate MSI installer
      run: |
        echo "MSI packaging script here"

    - name: Upload TellesoftOffice.msi
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOffice.msi
        path: TellesoftOffice.msi
