name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Locate VsDevCmd.bat
      id: find-vs
      shell: powershell
      run: |
        $vsPath = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" `
          -latest -products * -requires Microsoft.Component.MSBuild `
          -find "Common7\Tools\VsDevCmd.bat"
        echo "VS_PATH=$vsPath" >> $env:GITHUB_ENV

    - name: Prepare autogen.input
      shell: bash
      run: echo "PKG_CONFIG=/usr/bin/pkgconf" > autogen.input

    - name: Run autogen.sh with MSYS2 + Visual Studio
      shell: cmd
      run: |
        call "%VS_PATH%" && ^
        C:\msys64\usr\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && ./autogen.sh"

    - name: Build Tellesoft Office
      shell: cmd
      run: |
        call "%VS_PATH%" && ^
        C:\msys64\usr\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && make -j$(nproc)"

    - name: Generate MSI installer
      shell: bash
      run: |
        cd $(cygpath -u "${{ github.workspace }}")
        make install

    - name: Upload TellesoftOffice.msi
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOffice.msi
        path: '**/TellesoftOffice.msi'
