name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Cygwin and required packages
        uses: cygwin/cygwin-install-action@v4
        with:
          packages: >-
            make
            gcc-core
            gcc-g++
            autoconf
            automake
            libtool
            pkg-config
            git
            unzip
            zip
            perl
            bison
            flex
            gperf
            python3
            wget
            curl

      - name: Prepare autogen input
        run: echo '--with-theme=colibre' > autogen.input
        shell: bash

      - name: Run autogen.sh using Cygwin
        shell: bash
        run: |
          cd "$(cygpath -u "$GITHUB_WORKSPACE")"
          ./autogen.sh < autogen.input

      - name: Build LibreOffice (Tellesoft Office)
        shell: bash
        run: |
          cd "$(cygpath -u "$GITHUB_WORKSPACE")"
          make

      - name: Package Installer (MSI)
        shell: bash
        run: |
          cd "$(cygpath -u "$GITHUB_WORKSPACE")"
          make msicreator
          mv instdir/TellesoftOffice.msi .

      - name: Upload TellesoftOffice.msi
        uses: actions/upload-artifact@v3
        with:
          name: TellesoftOfficeInstaller
          path: TellesoftOffice.msi
