name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install MSYS2 and tools
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >
          base-devel
          autoconf
          automake
          make
          pkg-config
          git
          zip
          unzip

    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Run autogen.sh with MSYS2
      shell: msys2 {0}
      run: |
        ./autogen.sh \
          --with-theme=colibre \
          --disable-firebird-sdbc \
          --disable-ccache \
          --enable-release-build=yes \
          --with-java \
          --with-package-format=msi \
          --enable-option-checking=fatal

    - name: Build Tellesoft Office
      shell: msys2 {0}
      run: |
        make -j$(nproc)

    - name: Generate MSI installer
      shell: msys2 {0}
      run: |
        make installer

    - name: Upload TellesoftOffice.msi
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOffice.msi
        path: instdir/install/en-US/TellesoftOffice.msi
