name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install Cygwin with required packages
  uses: cygwin/cygwin-install-action@v4
  with:
    packages: >-
      git make gcc-core gcc-g++ perl python3 autoconf automake
      libtool gettext pkg-config m4 unzip zip tar bison flex

    - name: Prepare autogen.input
      run: echo '--with-theme=colibre' > autogen.input
      shell: bash

    - name: Run autogen.sh using Cygwin
      run: |
        C:\cygwin\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && ./autogen.sh"
      shell: cmd

    - name: Build LibreOffice (Tellesoft Office)
      run: |
        C:\cygwin\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && make build-nocheck"
      shell: cmd

    - name: Create MSI Installer (instsetoo_native)
      run: |
        C:\cygwin\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && make instsetoo_native"
      shell: cmd

    - name: Rename and move MSI
      run: |
        mkdir -p output
        copy workdir\instsetoo_native\install\en-US\LibreOffice_*.msi output\TellesoftOffice.msi
      shell: cmd

    - name: Upload TellesoftOffice.msi
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOffice
        path: output/TellesoftOffice.msi
