name: Build Tellesoft Office (Windows MSI)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install Cygwin with required packages
      uses: cygwin/cygwin-install-action@v4
      with:
        packages: >-
          git make gcc-core gcc-g++ perl python3 autoconf automake
          libtool gettext pkg-config m4 unzip zip tar bison flex

    - name: Set up MSBuild (Visual Studio)
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Prepare autogen.input
      shell: bash
      run: |
        echo '--with-theme=colibre' > autogen.input

    - name: Run autogen.sh using Cygwin + Visual Studio
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && ^
        C:\cygwin\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && ./autogen.sh"

    - name: Build LibreOffice (Tellesoft Office)
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && ^
        C:\cygwin\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && make build-nocheck"

    - name: Create MSI Installer (instsetoo_native)
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && ^
        C:\cygwin\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && make instsetoo_native"

    - name: Rename and move MSI
      shell: cmd
      run: |
        mkdir output
        for /r %%f in (workdir\instsetoo_native\**\LibreOffice_*.msi) do copy "%%f" "output\TellesoftOffice.msi"

    - name: Upload MSI artifact
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOffice
        path: output/TellesoftOffice.msi
