      - name: Install Cygwin for bash
        uses: cygwin/cygwin-install-action@v4
        with:
          packages: >-
            bash
            unzip
            zip
            tar
            bison
            flex
            autoconf
            automake
            m4
            pkg-config
            dos2unix

      - name: Convert autogen.sh line endings
        run: |
          C:\cygwin\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && dos2unix autogen.sh"
        shell: cmd

      - name: Run autogen.sh
        run: |
          C:\cygwin\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && ./autogen.sh"
        shell: cmd
