name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Download and extract MSYS2 manually
      shell: cmd
      run: |
        curl -L -o msys2.tar.xz https://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20240128.tar.xz
        7z e msys2.tar.xz -aoa -omsys2-temp
        7z x msys2-temp\msys2.tar -omsys2 -aoa

    - name: Set up MSVC environment
      shell: cmd
      run: |
        echo call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" > vsenv.bat
        echo msys2\usr\bin\bash.exe --login -c "cd %GITHUB_WORKSPACE% && ./autogen.sh" >> vsenv.bat

    - name: Run autogen.sh using MSYS2 bash
      shell: cmd
      run: |
        msys2\usr\bin\bash.exe --login -c "cd $GITHUB_WORKSPACE && ./autogen.sh"

    - name: Build Tellesoft Office
      shell: cmd
      run: |
        msys2\usr\bin\bash.exe --login -c "cd $GITHUB_WORKSPACE && make"

    - name: Generate MSI installer
      run: echo "MSI packaging logic"

    - name: Upload TellesoftOffice.msi
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOffice.msi
        path: TellesoftOffice.msi
