name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Post Checkout source code
        uses: actions/checkout@v4

      - name: Install Cygwin and packages
        uses: cygwin/cygwin-install-action@v4
        with:
          packages: >-
            autoconf
            automake
            libtool
            m4
            pkgconf
            make
            gcc-core
            gcc-g++
            bison
            flex
            perl
            python3
            git
            unzip
            zip
            which
            wget
            gettext-devel

      - name: Prepare autogen.input
        run: echo '--with-theme=colibre' > autogen.input

      - name: Run autogen.sh using Cygwin
        shell: cmd
        run: C:\cygwin64\bin\bash -lc "cd $PWD && ./autogen.sh"

      - name: Build LibreOffice (Tellesoft Office)
        shell: cmd
        run: C:\cygwin64\bin\bash -lc "cd $PWD && make"

      - name: Package Installer (MSI)
        shell: cmd
        run: C:\cygwin64\bin\bash -lc "cd $PWD && make package"

      - name: Upload TellesoftOffice.msi
        uses: actions/upload-artifact@v4
        with:
          name: TellesoftOffice
          path: '**/TellesoftOffice.msi'
