name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install required build tools
        run: |
          choco install make --yes
          choco install winflexbison3 --yes
          choco install wget --yes
          choco install unzip --yes
          choco install patch --yes
          choco install msys2 --yes

      - name: Install autotools with MSYS2
        run: |
          C:\tools\msys64\usr\bin\bash.exe -lc "pacman -Syu --noconfirm"
          C:\tools\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm autoconf automake libtool m4 gettext"

      - name: Set up MSVC environment
        run: |
          echo call "\"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat\"" > vsenv.bat

      - name: Run autogen.sh with MSVC
        shell: cmd
        run: |
          call vsenv.bat
          C:\tools\msys64\usr\bin\bash.exe -lc "./autogen.sh --with-theme=colibre --disable-firebird-sdbc --disable-ccache --enable-release-build=yes --with-java --with-package-format=msi --enable-option-checking=fatal"

      - name: Build Tellesoft Office
        shell: cmd
        run: |
          call vsenv.bat
          make build-nocheck

      - name: Generate MSI installer
        shell: cmd
        run: |
          call vsenv.bat
          make installer

      - name: Upload TellesoftOffice.msi
        uses: actions/upload-artifact@v4
        with:
          name: TellesoftOffice.msi
          path: instdir/TellesoftOffice.msi
