name: Build Tellesoft Office MSI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Prepare autogen.input
        run: |
          echo --with-theme=colibre > autogen.input
          echo --disable-firebird-sdbc >> autogen.input
          echo --disable-ccache >> autogen.input
          echo --with-jdk-home="C:/Program Files/Eclipse Adoptium/jdk-17" >> autogen.input
          echo --with-visual-studio=2022 >> autogen.input
          echo --with-windows-sdk=10.0 >> autogen.input
          echo --enable-release-build=yes >> autogen.input
        shell: cmd

      - name: Run autogen.sh using MSVC environment
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" ^
          && bash ./autogen.sh
        shell: cmd

      - name: Build LibreOffice (Tellesoft Office)
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" ^
          && make build-nocheck
        shell: cmd

      - name: Generate MSI installer
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" ^
          && make instsetoo_native
        shell: cmd

      - name: Collect MSI output
        run: |
          mkdir output
          copy workdir\instsetoo_native\install\en-US\LibreOffice_*.msi output\TellesoftOffice.msi
        shell: cmd

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: TellesoftOffice
          path: output/TellesoftOffice.msi
