name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up MSYS2 for autotools & deps
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: true
        install: |
          base-devel
          git
          autoconf
          automake
          libtool
          pkgconf
          make
          sed
          grep
          perl

    - name: Install Visual Studio Build Tools 2022
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        vs-version: 'latest'
        msbuild: true

    - name: Prepare autogen.input
      run: echo "--disable-firebird-sdbc" >> autogen.input

    - name: Run autogen.sh inside MSYS2
      shell: msys2 {0}
      run: |
        export PKG_CONFIG=$(which pkgconf)
        ./autogen.sh --with-lang=en-US --disable-firebird-sdbc

    - name: Build LibreOffice
      shell: msys2 {0}
      run: make

    - name: Package Installer (MSI)
      shell: msys2 {0}
      run: make msinstaller INSTDIR=instdir MSI_NAME=TellesoftOffice.msi

    - name: Upload MSI Installer
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOffice-installer
        path: instdir/TellesoftOffice.msi
