name: Build Tellesoft Office (Windows)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install Cygwin with required packages
      uses: cygwin/cygwin-install-action@v4
      with:
        packages: >-
          git make gcc-core gcc-g++ perl python3 autoconf automake
          libtool gettext pkg-config m4 unzip zip tar bison flex
          dos2unix wget

    - name: Add Cygwin to PATH
      shell: bash
      run: echo "C:/cygwin/bin" >> $GITHUB_PATH

    - name: Fix /bin/sh symlink for Cygwin
      shell: bash
      run: |
        if [ ! -e /bin/sh ]; then
          ln -s /bin/bash /bin/sh
        fi

    - name: Convert line endings (fix CRLF issues)
      shell: bash
      run: |
        if [ -f ./autogen.sh ]; then
          dos2unix ./autogen.sh
        fi

    - name: Install LibreOffice MSVC-compatible make
      shell: bash
      run: |
        wget -O /tmp/make.exe https://dev-www.libreoffice.org/bin/cygwin/make-4.2.1-msvc.exe
        mkdir -p /opt/lo/bin
        mv /tmp/make.exe /opt/lo/bin/make.exe
        chmod +x /opt/lo/bin/make.exe
        echo "/opt/lo/bin" >> $GITHUB_PATH

    - name: Prepare autogen.input
      shell: bash
      run: echo '--with-theme=colibre' > autogen.input

    - name: Set up Java (Temurin JDK 17)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up MSVC environment (VS 2022)
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64

    - name: Run autogen.sh using Cygwin + Visual Studio
      shell: cmd
      run: |
        C:\cygwin\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && ./autogen.sh --with-theme=colibre"

    - name: Build LibreOffice (Tellesoft Office)
      shell: cmd
      run: |
        C:\cygwin\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && make"

    - name: Create MSI Installer (instsetoo_native)
      shell: cmd
      run: |
        C:\cygwin\bin\bash.exe -lc "cd $(cygpath -u '${{ github.workspace }}') && cd instsetoo_native && make"

    - name: Rename and move MSI
      shell: bash
      run: |
        mkdir -p dist
        find ./instdir -name '*.msi' -exec cp {} ./dist/TellesoftOffice.msi \;

    - name: Upload MSI artifact
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOfficeInstaller
        path: dist/TellesoftOffice.msi
