name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up MSBuild (preinstalled use only)
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Install MSYS2 and build tools
      uses: msys2/setup-msys2@v2
      with:
        install: >-
          base-devel
          mingw-w64-x86_64-pkgconf
          autoconf
          automake
          m4
          tar
        msystem: MINGW64

    - name: Prepare autogen.input
      run: |
        echo '--with-theme=colibre' > autogen.input
        echo '--enable-release-build' >> autogen.input
        echo '--disable-compiler-plugins' >> autogen.input
      shell: bash

    - name: Run autogen.sh in MSYS2
      shell: msys2 {0}
      run: |
        ./autogen.sh

    - name: Build LibreOffice (Tellesoft Office)
      shell: msys2 {0}
      run: |
        make build-nocheck -j$(nproc)

    - name: Package Installer (MSI)
      shell: msys2 {0}
      run: |
        make MSI_PACKAGE=1

    - name: Upload TellesoftOffice.msi
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOffice
        path: instdir/TellesoftOffice.msi
