name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up MSBuild (preinstalled use only)
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Install pkgconf (required by LibreOffice)
      run: |
        Invoke-WebRequest -Uri https://distfiles.dereferenced.org/pkgconf/pkgconf-1.9.5.tar.xz -OutFile pkgconf.tar.xz
        tar -xf pkgconf.tar.xz
        echo "${{ github.workspace }}\pkgconf-1.9.5" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh

    - name: Prepare autogen.input
      run: |
        echo '--with-theme=colibre' > autogen.input
        echo '--enable-release-build' >> autogen.input
      shell: pwsh

    - name: Run autogen.sh in MSYS2
      run: |
        C:\msys64\usr\bin\bash.exe -lc "cd $PWD && ./autogen.sh"

    - name: Build LibreOffice (Tellesoft Office)
      run: |
        C:\msys64\usr\bin\bash.exe -lc "cd $PWD && make build-nocheck -j$(nproc)"

    - name: Package Installer (MSI)
      run: |
        C:\msys64\usr\bin\bash.exe -lc "cd $PWD && make MSI_PACKAGE=1"

    - name: Upload TellesoftOffice.msi
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOffice
        path: instdir/TellesoftOffice.msi
