name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install Cygwin with required packages
      uses: cygwin/cygwin-install-action@v4
      with:
        packages: >-
          git make gcc-core gcc-g++ perl python3 autoconf automake
          libtool gettext pkg-config m4 unzip zip tar bison flex
          dos2unix wget

    - name: Add Cygwin to PATH
      run: echo "C:\cygwin\bin" >> $env:GITHUB_PATH
      shell: pwsh

    - name: Prepare autogen.input
      run: echo '--with-theme=colibre' > autogen.input
      shell: bash

    - name: Convert line endings (fix CRLF issues)
      run: dos2unix autogen.sh
      shell: bash

    - name: Install LibreOffice MSVC-compatible make
      shell: bash
      run: |
        set -e
        wget -O /tmp/make-4.2.1-msvc.exe https
