name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Download and install MSYS2
      run: |
        Invoke-WebRequest -Uri https://github.com/msys2/msys2-installer/releases/download/2023-05-26/msys2-base-x86_64-20230526.sfx.exe -OutFile msys2.exe
        .\msys2.exe -y
        echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install pkgconf inside MSYS2
      run: |
        C:\msys64\usr\bin\bash.exe -lc "pacman -Sy --noconfirm pkgconf"

    - name: Prepare autogen.input
      run: |
        echo '--with-theme=colibre' > autogen.input
        echo '--enable-release-build' >> autogen.input

    - name: Run autogen.sh inside MSYS2
      run: |
        C:\msys64\usr\bin\bash.exe -lc "cd $PWD && ./autogen.sh"

    - name: Build LibreOffice (Tellesoft Office)
      run: |
        C:\msys64\usr\bin\bash.exe -lc "cd $PWD && make build-nocheck -j$(nproc)"

    - name: Package Installer (MSI)
      run: |
        C:\msys64\usr\bin\bash.exe -lc "cd $PWD && make MSI_PACKAGE=1"

    - name: Upload TellesoftOffice.msi
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOffice
        path: instdir/TellesoftOffice.msi
