name: Build Tellesoft Office MSI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install required build tools
        run: |
          choco install strawberryperl --no-progress -y
          choco install nasm --no-progress -y
          choco install jdk17 --no-progress -y
          choco install make --no-progress -y
        shell: powershell

      - name: Run autogen.sh using MSVC + Git Bash
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          "C:\Program Files\Git\bin\bash.exe" ./autogen.sh
        shell: cmd

      - name: Build LibreOffice (Tellesoft Office)
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          make build-nocheck
        shell: cmd

      - name: Generate MSI installer
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          make instsetoo_native
        shell: cmd

      - name: Upload TellesoftOffice.msi
        uses: actions/upload-artifact@v4
        with:
          name: TellesoftOffice-Installer
          path: workdir/instsetoo_native/install/en-US/*.msi
