name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install Cygwin and packages
      uses: cygwin/cygwin-install-action@v4
      with:
        packages: >-
          make
          gcc-core
          gcc-g++
          perl
          python3
          unzip
          zip
          git
          pkg-config
          libtool
          automake
          autoconf
          bison
          flex
          patch
          diffutils

    - name: Prepare autogen.input
      run: echo '--with-theme=colibre' > autogen.input

    - name: Run autogen.sh using Cygwin
      shell: cmd
      run: >
        C:\cygwin64\bin\bash -lc "cd $(cygpath -u '${{ github.workspace }}') && ./autogen.sh"

    - name: Build LibreOffice (Tellesoft Office)
      shell: cmd
      run: >
        C:\cygwin64\bin\bash -lc "cd $(cygpath -u '${{ github.workspace }}') && make build-nocheck"

    - name: Create Installer (MSI via instsetoo_native)
      shell: cmd
      run: >
        C:\cygwin64\bin\bash -lc "cd $(cygpath -u '${{ github.workspace }}') && cd instsetoo_native && build --all"

    - name: Rename and Upload TellesoftOffice.msi
      run: |
        $src = Get-ChildItem -Recurse -Filter "*.msi" | Where-Object { $_.FullName -like "*install/en-US/*.msi" } | Select-Object -First 1
        if ($src) {
          Copy-Item $src.FullName TellesoftOffice.msi
        } else {
          Write-Error "MSI not found"
        }
      shell: pwsh

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOffice
        path: TellesoftOffice.msi
