name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install prerequisites with Chocolatey
        run: |
          choco install -y git 7zip ccache
          choco install -y --ignore-checksums make

      - name: Prepare build environment
        run: echo --disable-firebird-sdbc >> autogen.input

      - name: Set up Visual Studio environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure LibreOffice
        run: ./autogen.sh --with-parallelism=2 --disable-firebird-sdbc --enable-option-checking=fatal

      - name: Build LibreOffice
        run: make -j2

      - name: Package MSI installer
        run: |
          mkdir output
          copy instdir\*.msi output\

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: TellesoftOfficeInstaller
          path: output/
