name: build-windows

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        install: >-
          base-devel
          mingw-w64-x86_64-toolchain
          git
          autoconf
          automake
          libtool
          pkg-config
          make
          unzip
          wget
        msystem: MINGW64
        update: true

    - name: Configure and build
      shell: msys2 {0}
      run: |
        ./autogen.sh --with-parallelism=2 --disable-firebird-sdbc
        make build-nocheck

    - name: Package installer
      shell: msys2 {0}
      run: |
        make installer

    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: tellesoffice-windows-installer
        path: instdir/*.msi
