name: build

on:
  workflow_dispatch:

jobs:
  build:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          choco install -y git wget make ccache
          choco install -y "visualstudio2022buildtools" --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --includeRecommended --includeOptional"

      - name: Prepare build environment
        shell: bash
        run: echo --disable-firebird-sdbc >> autogen.input

      - name: Configure and build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          bash -c "./autogen.sh --with-parallelism=2 --disable-firebird-sdbc"

      - name: Compile LibreOffice
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          bash -c "make"

      - name: Package MSI installer
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          bash -c "make package"

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: tellesuite-windows-msi
          path: instdir/*.msi
