name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        shell: powershell
        run: |
          curl -o python-installer.exe https://www.python.org/ftp/python/3.11.9/python-3.11.9-amd64.exe
          Start-Process -FilePath "$PWD\python-installer.exe" -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1 Include_test=0" -Wait

      - name: Install winflexbison and 7zip manually
        shell: powershell
        run: |
          Invoke-WebRequest https://github.com/lexxmark/winflexbison/releases/download/v2.5.22/win_flex_bison-2.5.22.zip -OutFile winflexbison.zip
          Expand-Archive winflexbison.zip -DestinationPath $env:ProgramFiles
          $env:Path += ";$env:ProgramFiles\win_flex_bison-2.5.22"
          Invoke-WebRequest https://www.7-zip.org/a/7z2301-x64.exe -OutFile 7zip.exe
          Start-Process .\7zip.exe -ArgumentList "/S" -Wait

      - name: Set up MSVC environment
        uses: microsoft/setup-msbuild@v1.1

      - name: Prepare autogen.input
        run: echo --disable-firebird-sdbc >> autogen.input

      - name: Run autogen and configure
        run: |
          ./autogen.sh
          make fetch

      - name: Build LibreOffice
        run: make

      - name: Package MSI
        run: |
          mkdir output
          cp instdir/program/soffice.exe output/
          # Example packaging step – update as needed

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: output/
