name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild & Visual Studio environment
      uses: microsoft/setup-msbuild@v1

    - name: Install Chocolatey & prerequisites
      run: |
        choco feature enable -n allowGlobalConfirmation
        choco install make cmake git python ccache visualstudio-installer

    - name: Prepare autogen.input
      shell: bash
      run: echo "--disable-firebird-sdbc" > autogen.input

    - name: Bootstrap / configure
      shell: bash
      run: |
        ./autogen.sh --with-parallelism=4 --disable-firebird-sdbc

    - name: Build LibreOffice
      shell: bash
      run: |
        make

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: libreoffice-windows
        path: /path/to/your/installer.msi
