name: build-windows

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        choco install -y ccache
        choco install -y ninja
        choco install -y git
        choco install -y make

    - name: Write autogen.input
      run: |
        echo --disable-firebird-sdbc >> autogen.input
        echo --disable-pdfium >> autogen.input
        echo --with-parallelism=2 >> autogen.input

    - name: Configure with autogen
      shell: bash
      run: |
        ./autogen.sh

    - name: Build with make
      shell: bash
      run: |
        make build-nocheck

    - name: Package installer
      shell: bash
      run: |
        make installer

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tellesoffice-windows-installer
        path: instdir/*.msi
