
name: build-windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install prerequisites with Chocolatey
      run: |
        choco install -y cygwin
        choco install -y make
        choco install -y visualstudio2022buildtools
        choco install -y git python3
        choco install -y ccache

    - name: Add Cygwin to PATH
      run: |
        echo "C:\tools\cygwin\bin" >> $env:GITHUB_PATH

    - name: Prepare autogen.input
      run: echo '--disable-firebird-sdbc' >> autogen.input

    - name: Configure with autogen.sh
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
        bash ./autogen.sh

    - name: Build LibreOffice (Tellesoft)
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
        make

    - name: Upload MSI Installer
      uses: actions/upload-artifact@v4
      with:
        name: tellesuite-windows-msi
        path: instdir
