name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Post Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install MSYS2 just to install Unix dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            base-devel
            autoconf
            automake
            libtool
            pkg-config
            make
            sed
            grep
            flex
            bison

      - name: Copy Unix tools to Windows PATH
        shell: cmd
        run: |
          set PATH=C:\msys64\usr\bin;%PATH%

      - name: Prepare autogen.input
        run: echo "--disable-firebird-sdbc" >> autogen.input
        shell: bash
        working-directory: ${{ github.workspace }}

      - name: Run autogen.sh inside Developer Command Prompt
        shell: cmd
        run: |
          "C:\BuildTools\Common7\Tools\VsDevCmd.bat" ^
          && bash autogen.sh
        working-directory: ${{ github.workspace }}

      - name: Show autogen.log
        shell: cmd
        run: type autogen.log
        working-directory: ${{ github.workspace }}

      - name: Build LibreOffice
        shell: cmd
        run: |
          "C:\BuildTools\Common7\Tools\VsDevCmd.bat" ^
          && make
        working-directory: ${{ github.workspace }}

      - name: Package MSI
        if: always()
        run: echo "Stub for packaging"

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: built-output
          path: build
