name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        shell: powershell
        run: |
          curl -o python-installer.exe https://www.python.org/ftp/python/3.11.9/python-3.11.9-amd64.exe
          Start-Process -FilePath "python-installer.exe" -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1 Include_test=0" -Wait

      - name: Install winflexbison and 7zip manually
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://github.com/lexxmark/winflexbison/releases/download/v2.5.22/win_flex_bison-2.5.22.zip -OutFile flexbison.zip
          Expand-Archive flexbison.zip -DestinationPath C:\winflexbison
          echo "C:\winflexbison" | Out-File -Append $env:GITHUB_PATH
          
          Invoke-WebRequest -Uri https://www.7-zip.org/a/7z2301-x64.exe -OutFile 7zip.exe
          Start-Process -FilePath ".\7zip.exe" -ArgumentList "/S" -Wait

      - name: Set up MSVC environment
        uses: microsoft/setup-msbuild@v1.1

      - name: Prepare autogen.input
        shell: bash
        run: echo "--disable-firebird-sdbc" >> autogen.input

      - name: Run autogen and configure
        shell: bash
        run: |
          ./autogen.sh

      - name: Build LibreOffice
        shell: bash
        run: |
          make build-nocheck

      - name: Package MSI
        shell: bash
        run: |
          make package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TellesoftOfficeInstaller
          path: instdir
