name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install winflexbison and 7zip manually
      run: |
        curl -LO https://github.com/lexxmark/winflexbison/releases/download/v2.5.22/win_flex_bison-2.5.22.zip
        curl -LO https://www.7-zip.org/a/7z2301-x64.exe
        Start-Process .\7z2301-x64.exe -ArgumentList "/S" -NoNewWindow -Wait
        & "C:\Program Files\7-Zip\7z.exe" x win_flex_bison-2.5.22.zip -oC:\winflexbison
        echo "C:\winflexbison" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

    - name: Install Visual Studio Build Tools 2022 with required components
      run: |
        curl -LO https://aka.ms/vs/17/release/vs_BuildTools.exe
        Start-Process .\vs_BuildTools.exe -ArgumentList '--quiet', '--wait', '--norestart', '--nocache', `
          '--installPath', 'C:\BuildTools', `
          '--add', 'Microsoft.VisualStudio.Workload.VCTools', `
          '--add', 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64', `
          '--add', 'Microsoft.VisualStudio.Component.Windows10SDK.20348' `
          -NoNewWindow -Wait

    - name: Set up MSYS2 just to install Unix dependencies
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: true
        install: >-
          autoconf
          automake
          make
          libtool
          pkgconf
          sed
          grep
          perl
          git

    - name: Copy Unix tools to Windows PATH
      run: |
        echo "C:\msys64\usr\bin" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

    - name: Prepare autogen.input
      run: echo "--disable-firebird-sdbc" >> autogen.input

    - name: Run autogen.sh inside Developer Command Prompt
      shell: cmd
      run: |
        "C:\BuildTools\Common7\Tools\VsDevCmd.bat" ^
        && call autogen.sh --with-lang=en-US --disable-firebird-sdbc

    - name: Build LibreOffice
      shell: cmd
      run: |
        "C:\BuildTools\Common7\Tools\VsDevCmd.bat" ^
        && call make

    - name: Package MSI
      shell: cmd
      run: |
        "C:\BuildTools\Common7\Tools\VsDevCmd.bat" ^
        && call make msinstaller

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tellesuite-windows-msi
        path: instdir\*.msi
