name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install winflexbison and 7zip manually
      run: |
        curl -L -o winflexbison.zip https://github.com/lexxmark/winflexbison/releases/download/v2.5.22/win_flex_bison-2.5.22.zip
        7z x winflexbison.zip -owinflexbison
        echo "${{ github.workspace }}\\winflexbison" | Out-File -FilePath $env:GITHUB_PATH -Append
        curl -L -o pkgconf.exe https://github.com/pkgconf/pkgconf/releases/download/pkgconf-2.0.3/pkgconf.exe
        mkdir pkgconf-bin
        move pkgconf.exe pkgconf-bin\
        echo "${{ github.workspace }}\\pkgconf-bin" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: 'latest'

    - name: Set up MSYS2 (for tools, not shell)
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          make
          tar
          pkg-config
          autoconf
          automake
          libtool
          unzip
          mingw-w64-x86_64-libxslt
          mingw-w64-x86_64-tools

    - name: Prepare autogen.input
      run: echo "--disable-firebird-sdbc" >> autogen.input

    - name: Run autogen.sh inside MSYS2 Bash
      shell: msys2 {0}
      run: |
        export PATH="$PATH:/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/MSBuild/Current/Bin"
        export PATH="$PATH:/c/msys64/mingw64/bin"
        export PKG_CONFIG="${{ github.workspace }}/pkgconf-bin/pkgconf.exe"
        ./autogen.sh

    - name: Build LibreOffice
      run: |
        echo "Simulated build step. Replace this with actual build commands."

    - name: Package MSI
      run: |
        echo "Simulated packaging step. Replace this with actual packaging commands."

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: build/
