name: build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python
      run: |
        curl.exe -L -o $env:TEMP\python-installer.exe https://www.python.org/ftp/python/3.11.9/python-3.11.9-amd64.exe
        Start-Process -Wait -FilePath "$env:TEMP\python-installer.exe" -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1 Include_test=0"

    - name: Install winflexbison and 7zip manually
      run: |
        curl.exe -L -o winflexbison.zip https://github.com/lexxmark/winflexbison/releases/download/v2.5.22/win_flex_bison-2.5.22.zip
        7z x winflexbison.zip -owinflexbison
        echo "C:\\winflexbison" | Out-File -Append $env:GITHUB_PATH

    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Set up MSYS2 (for tools, not shell)
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          git
          autoconf
          automake
          mingw-w64-x86_64-libxslt
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-make

    - name: Prepare autogen.input
      run: echo "--disable-firebird-sdbc" >> autogen.input

    - name: Run autogen and configure (MSVC native)
      shell: msys2 {0}
      run: |
        export PATH="$PATH:/c/winflexbison"
        ./autogen.sh --disable-firebird-sdbc --enable-option-checking=fatal

    - name: Build LibreOffice
      shell: msys2 {0}
      run: |
        make

    - name: Package MSI
      shell: bash
      run: |
        echo "MSI packaging step goes here"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Tellesoft-Office-Installer
        path: ./instsetoo_native
