name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Chocolatey packages
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          choco install -y cygwin
          choco install -y make git unzip python3

      - name: Setup Cygwin environment
        run: |
          $env:Path += ";C:\tools\cygwin\bin"
          C:\tools\cygwin\setup-x86_64.exe -q -P make,gcc-g++,git,python3,autoconf,automake,libtool,unzip,tar

      - name: Configure and bootstrap
        shell: bash
        run: |
          ./autogen.sh --with-parallelism=4 \
            --without-help \
            --without-myspell-dicts \
            --disable-firebird-sdbc \
            --disable-odk \
            --disable-postgresql-sdbc \
            --disable-dconf \
            --disable-gstreamer-1-0 \
            --disable-sdremote \
            --disable-scripting-beanshell \
            --disable-scripting-javascript \
            --disable-xmlsecurity \
            --disable-lpsolve \
            --disable-collada \
            --disable-coinmp \
            --disable-evolution2 \
            --disable-gio \
            --disable-kf5 \
            --disable-gtk3 \
            --disable-qt5 \
            --disable-firebird \
            --disable-gtk3-kde5 \
            --disable-gio \
            --disable-dbus

      - name: Build Tellesoft Office
        shell: bash
        run: |
          make -j$(nproc)

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: tellesoffice-windows-build
          path: instdir
