name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install Visual Studio Build Tools 2022 with required components
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Install 7zip
      run: |
        Invoke-WebRequest https://www.7-zip.org/a/7z2301-x64.exe -OutFile 7z.exe
        Start-Process .\7z.exe -ArgumentList "/S" -Wait
        echo "C:\Program Files\7-Zip" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install MSYS2 manually (no Chocolatey)
      run: |
        Invoke-WebRequest -Uri https://github.com/msys2/msys2-installer/releases/download/2023-10-26/msys2-base-x86_64-20231026.tar.xz -OutFile msys2.tar.xz
        7z x msys2.tar.xz -aoa -omsys2.tar
        7z x msys2.tar -aoa -omsys64
        echo "$env:GITHUB_WORKSPACE\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "$env:GITHUB_WORKSPACE\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Prepare autogen.input
      run: |
        echo '--with-lang=en-US' > autogen.input
        echo '--with-theme=colibre' >> autogen.input
        echo '--enable-release-build' >> autogen.input
        echo '--disable-online-update' >> autogen.input
        echo '--disable-breakpad' >> autogen.input
        echo '--with-product-name=Tellesoft Office' >> autogen.input
        echo '--with-vendor=Tellesoft' >> autogen.input
        echo '--with-build-version=Tellesoft Professional Edition' >> autogen.input

    - name: Run autogen.sh inside MSYS2
      shell: cmd
      run: |
        C:\msys64\usr\bin\bash.exe -lc "./autogen.sh"

    - name: Build LibreOffice
      shell: cmd
      run: |
        C:\msys64\usr\bin\bash.exe -lc "make build-nocheck"

    - name: Package Installer (MSI)
      shell: cmd
      run: |
        C:\msys64\usr\bin\bash.exe -lc "make pkg"

    - name: Upload build directory
      uses: actions/upload-artifact@v4
      with:
        name: build-directory
        path: instdir/

    - name: Upload MSI installer
      uses: actions/upload-artifact@v4
      with:
        name: tellesofft-office-installer
        path: workdir/installation/LibreOffice*/*.msi
