name: Windows Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    env:
      LO_SOURCE_DIR: ${{ github.workspace }}\office-core
      LO_OUTPUT_DIR: ${{ github.workspace }}\build
      PYTHON: C:\Python311

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        run: |
          curl -o python-installer.exe https://www.python.org/ftp/python/3.11.9/python-3.11.9-amd64.exe
          python-installer.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0
          echo "Python installed at: %PYTHON%"

      - name: Install winflexbison and 7zip manually
        run: |
          curl -L -o winflexbison.zip https://github.com/lexxmark/winflexbison/releases/download/v2.5.22/win_flex_bison-2.5.22.zip
          7z x winflexbison.zip -owinflexbison
          echo "${{ github.workspace }}\winflexbison" >> $GITHUB_PATH

          curl -L -o 7zip.msi https://www.7-zip.org/a/7z2201-x64.msi
          msiexec /quiet /i 7zip.msi

      - name: Set up MSVC environment
        shell: cmd
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && set

      - name: Prepare autogen.input
        run: |
          echo --disable-firebird-sdbc >> autogen.input
          echo --with-external-tar="${{ github.workspace }}\externals" >> autogen.input

      - name: Run autogen and configure
        shell: cmd
        run: |
          cd office-core
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          ./autogen.sh --with-external-tar="${{ github.workspace }}\externals"

      - name: Build LibreOffice
        shell: cmd
        run: |
          cd office-core
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          make

      - name: Package MSI
        shell: cmd
        run: |
          cd instsetoo_native
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          build

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: tellesoffice-windows-msi
          path: office-core/instsetoo_native/**/install/en-US/*.msi
