name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up job
        run: echo "Starting Windows Build..."

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install prerequisites with Chocolatey
        run: |
          choco install -y make
          choco install -y ninja
          choco install -y ccache
          choco install -y zip

      - name: Prepare build environment
        run: echo --disable-firebird-sdbc >> autogen.input

      - name: Set up Visual Studio environment
        shell: cmd
        run: |
          "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

      - name: Configure LibreOffice
        run: |
          ./autogen.sh --enable-win64 --disable-firebird-sdbc --with-lang=en-US --with-product-name="Tellesoft Office" --with-vendor="Tellesoft Inc." --enable-dbgutil

      - name: Build LibreOffice
        run: make

      - name: Package MSI installer
        run: |
          instdir/program/soffice.exe --headless --convert-to msi *.msi

      - name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          name: tellesuite-installer
          path: instdir/**/*.msi

      - name: Post Set up Python
        run: python --version

      - name: Post Checkout source code
        run: git version

      - name: Complete job
        run: echo "Build process complete"
