name: build-windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Chocolatey prerequisites
        run: |
          choco install -y git make wget unzip zip
          choco install -y visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended --includeOptional"

      - name: Set up Visual Studio environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure build
        shell: pwsh
        run: |
          .\autogen.sh --with-parallelism=2 --disable-firebird-sdbc

      - name: Build LibreOffice (Tellesoft Office)
        shell: pwsh
        run: |
          make -j2

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: tellesoft-office-windows
          path: instdir
