      - name: Build LibreOffice
        shell: msys2 {0}
        run: make build-nocheck

      - name: Package MSI
        shell: msys2 {0}
        run: make package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TellesoftOfficeInstaller
          path: instdir
