
name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install winflexbison and 7zip manually
      run: |
        curl -LO https://github.com/lexxmark/winflexbison/releases/download/v2.5.22/win_flex_bison-2.5.22.zip
        7z x win_flex_bison-2.5.22.zip -oC:\winflexbison
        echo "C:\winflexbison" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

    - name: Install Visual Studio Build Tools 2022 with required components
      run: |
        curl -LO https://aka.ms/vs/17/release/vs_BuildTools.exe
        Start-Process .\vs_BuildTools.exe -ArgumentList '--quiet', '--wait', '--norestart', '--nocache', `
          '--installPath', 'C:\BuildTools', `
          '--add', 'Microsoft.VisualStudio.Workload.VCTools', `
          '--add', 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64', `
          '--add', 'Microsoft.VisualStudio.Component.Windows10SDK.20348' `
          -NoNewWindow -Wait

    - name: Set up MSYS2 for autotools
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: true
        install: >-
          base-devel
          git
          autoconf
          automake
          libtool
          pkgconf
          make
          sed
          grep
          perl

    - name: Prepare autogen.input
      run: echo "--disable-firebird-sdbc" >> autogen.input

    - name: Run autogen.sh inside MSYS2 Bash
      shell: msys2 {0}
      run: |
        export PATH="/c/BuildTools/VC/Tools/MSVC/14.*/bin/Hostx64/x64:$PATH"
        export PKG_CONFIG=$(which pkgconf)
        ./autogen.sh --with-lang=en-US --disable-firebird-sdbc

    - name: Build LibreOffice
      shell: msys2 {0}
      run: make

    - name: Package MSI
      shell: msys2 {0}
      run: make msinstaller

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tellesuite-windows-msi
        path: instdir/*.msi
