name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install prerequisites with Chocolatey
        run: |
          choco install -y zip unzip make perl wget
          refreshenv

      - name: Prepare build environment
        run: echo --disable-firebird-sdbc >> autogen.input

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Configure LibreOffice
        run: |
          ./autogen.sh --with-external-tar=/tmp/lo-externalsrc \
                       --disable-firebird-sdbc \
                       --disable-online-update \
                       --enable-release-build \
                       --with-lang=en-US \
                       --without-java

      - name: Build LibreOffice
        run: |
          make -j4

      - name: Package MSI installer
        run: |
          instdir/program/soffice.exe --headless --convert-to pdf somefile.odt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tellesoft-Office-Win64
          path: instdir

