name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat'

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install Chocolatey packages
      run: |
        choco install -y make python winflexbison7 git cmake

    - name: Prepare autogen.input
      run: echo --disable-firebird-sdbc >> autogen.input

    - name: Initialize MSVC environment
      run: call "%MSBUILD_PATH%" && where cl

    - name: Run autogen and configure
      shell: bash
      run: |
        ./autogen.sh @autogen.input --enable-option-checking=fatal \
          --disable-java --disable-python \
          --host=x86_64-w64-mingw32

    - name: Build LibreOffice
      shell: bash
      run: make -j%NUMBER_OF_PROCESSORS%

    - name: Package MSI
      shell: bash
      run: make release-win64

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: LibreOffice-Windows
        path: instsetoo_Win_x64_install\*.msi
