name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install winflexbison and 7zip manually
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://github.com/lexxmark/winflexbison/releases/download/v2.5.22/win_flex_bison-2.5.22.zip" -OutFile "winflexbison.zip"
          Expand-Archive winflexbison.zip -DestinationPath "C:\winflexbison"
          echo "C:\winflexbison" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

          Invoke-WebRequest -Uri "https://www.7-zip.org/a/7z2301-x64.exe" -OutFile "7zsetup.exe"
          Start-Process -FilePath "7zsetup.exe" -ArgumentList "/S" -Wait

      - name: Set up MSVC environment
        uses: microsoft/setup-msbuild@v1.1

      - name: Set up MSYS2 (for tools, not shell)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
            autoconf
            automake
            libtool
            m4
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-libxslt
            mingw-w64-x86_64-ninja

      - name: Prepare autogen.input
        shell: bash
        run: |
          echo "--disable-firebird-sdbc" >> autogen.input

      - name: Run autogen and configure (MSVC native)
        shell: bash
        run: |
          export PATH="$PATH:/c/winflexbison"
          ./autogen.sh --with-visual-studio=2022 --disable-firebird-sdbc

      - name: Build LibreOffice
        shell: bash
        run: |
          make build-nocheck

      - name: Package MSI
        shell: bash
        run: |
          make package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TellesoftOfficeInstaller
          path: instdir
