name: build

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install prerequisites with Chocolatey
        run: |
          choco install -y make autoconf automake libtool ccache

      - name: Prepare build environment
        run: echo --disable-firebird-sdbc >> autogen.input

      - name: Configure LibreOffice
        shell: bash
        run: |
          ./autogen.sh --with-parallelism=2 --disable-firebird-sdbc

      - name: Build LibreOffice
        shell: bash
        run: |
          make build-nocheck

      - name: Package MSI installer
        shell: bash
        run: |
          make pkg-msi

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: tellesuite-msi
          path: instdir/install/*/*.msi
