name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install winflexbison and 7zip manually
      run: |
        curl -LO https://github.com/lexxmark/winflexbison/releases/download/v2.5.22/win_flex_bison-2.5.22.zip
        7z x win_flex_bison-2.5.22.zip -oC:\winflexbison
        echo "C:\winflexbison" >> $env:GITHUB_PATH

    - name: Set up MSVC environment
      uses: microsoft/setup-msbuild@v1.1

    - name: Set up MSYS2 (for tools, not shell)
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: true
        install: >-
          base-devel
          git
          autoconf
          automake
          libtool
          pkg-config
          make
          sed
          grep
          perl

    - name: Prepare autogen.input
      run: echo "--disable-firebird-sdbc" >> autogen.input

    - name: Run autogen and configure (MSVC native)
      shell: pwsh
      run: |
        $env:PATH += ";C:\winflexbison"
        bash -lc "./autogen.sh --with-lang=en-US --disable-firebird-sdbc"

    - name: Build LibreOffice
      shell: bash
      run: |
        make

    - name: Package MSI
      shell: bash
      run: |
        make msinstaller

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tellesuite-windows-msi
        path: instdir/*.msi
