name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install Visual Studio Build Tools 2022 with required components
      uses: microsoft/setup-msbuild@v1.1

    - name: Install 7zip
      run: |
        Invoke-WebRequest -Uri https://www.7-zip.org/a/7z2301-x64.exe -OutFile 7z.exe
        Start-Process -FilePath .\7z.exe -ArgumentList "/S" -NoNewWindow -Wait

    - name: Install MSYS2 manually (no Chocolatey)
      shell: powershell
      run: |
        $msysUrl = "https://mirror.msys2.org/distrib/x86_64/msys2-base-x86_64-20240106.tar.xz"
        Invoke-WebRequest -Uri $msysUrl -OutFile msys2.tar.xz
        7z x msys2.tar.xz -aoa -oC:\msys64 | Out-Null
        7z x C:\msys64\msys2.tar -aoa -oC:\msys64 | Out-Null
        echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Add Unix tools to Windows PATH
      run: |
        echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Prepare autogen.input
      run: echo '--with-product-name=Tellesoft Office --with-vendor=Tellesoft' > autogen.input

    - name: Run autogen.sh inside MSYS2
      shell: bash
      run: |
        /usr/bin/bash -lc "./autogen.sh --with-theme=colibre --with-help --without-myspell-dicts"

    - name: Build LibreOffice
      shell: bash
      run: |
        /usr/bin/bash -lc "make build-nocheck"

    - name: Package Installer (MSI)
      shell: bash
      run: |
        /usr/bin/bash -lc "make package"

    - name: Upload build directory
      uses: actions/upload-artifact@v4
      with:
        name: build-directory
        path: instdir/

    - name: Upload MSI installer
      uses: actions/upload-artifact@v4
      with:
        name: TellesoftOffice
        path: '**/TellesoftOffice.msi'
