name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install prerequisites
        run: |
          choco install -y make
          choco install -y ninja
          choco install -y zip

      - name: Prepare build environment
        run: echo --disable-firebird-sdbc >> autogen.input

      - name: Set up Visual Studio environment
        run: |
          call "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

      - name: Configure LibreOffice
        run: |
          bash ./autogen.sh --enable-win64 --with-lang=en-US --disable-firebird-sdbc --with-product-name="Tellesoft Office" --with-vendor="Tellesoft Inc."

      - name: Build LibreOffice
        run: |
          if exist Makefile (
            make
          ) else (
            echo ERROR: Makefile not found. autogen.sh probably failed.
            exit /b 1
          )

      - name: Package MSI
        run: |
          dir instdir
          echo Skipping packaging logic for now.

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tellesuite-installer
          path: instdir/**/*.msi
