name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Chocolatey and essential packages
      run: |
        choco install -y make cmake git 7zip
        Invoke-WebRequest -Uri "https://github.com/lexxmark/winflexbison/releases/download/v2.5.22/win_flex_bison-2.5.22.zip" -OutFile "winflexbison.zip"
        7z x winflexbison.zip -owinflexbison
        echo "${{ github.workspace }}\\winflexbison" | Out-File -Append -FilePath $env:GITHUB_PATH

    - name: Set up Visual Studio environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Prepare build environment
      run: echo --disable-firebird-sdbc >> autogen.input

    - name: Configure LibreOffice
      run: |
        ./autogen.sh --with-external-tar="${{ github.workspace }}/externals" ^
                     --disable-firebird-sdbc ^
                     --disable-odk ^
                     --disable-gpgmepp ^
                     --disable-online-update ^
                     --with-theme=colibre ^
                     --with-lang=en-US

    - name: Build LibreOffice
      run: make -j4

    - name: Package MSI installer
      run: |
        cd instsetoo_native
        build --all --msi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tellesuite-windows-installer
        path: instsetoo_native/**/install/*.msi
