name: build-windows

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Post Checkout source code
      uses: actions/checkout@v4

    - name: Install prerequisites
      shell: pwsh
      run: |
        choco install -y ninja
        choco install -y ccache

    - name: Configure and build
      shell: pwsh
      run: |
        ./autogen.sh
        ./configure --with-external-tar=external/tarballs --with-parallelism=4
        make

    - name: Package MSI installer
      shell: pwsh
      run: |
        make MSI

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: tellesoffice-windows-installer
        path: instdir/*.msi
