name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Visual Studio Build Tools 2022 with required components
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '2022'

      - name: Install 7-Zip
        run: |
          Invoke-WebRequest -Uri https://www.7-zip.org/a/7z2301-x64.exe -OutFile 7z.exe
          Start-Process .\7z.exe -ArgumentList "/S" -Wait

      - name: Install MSYS2 (manual, no Chocolatey)
        run: |
          Invoke-WebRequest -Uri https://github.com/msys2/msys2-installer/releases/latest/download/msys2-x86_64-20240120.exe -OutFile msys2-installer.exe
          Start-Process .\msys2-installer.exe -ArgumentList "--root C:\msys64 --confirm-command --no-start" -Wait
          echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Add Git Bash Unix tools to PATH
        run: |
          echo "C:\Program Files\Git\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Prepare autogen.input
        run: |
          echo '--enable-release-build=yes' > autogen.input
          echo '--with-branding=tellesoft' >> autogen.input

      - name: Run autogen.sh inside MSYS2
        shell: msys2 {0}
        run: |
          cd $GITHUB_WORKSPACE
          ./autogen.sh

      - name: Build LibreOffice (nocheck)
        shell: msys2 {0}
        run: |
          cd $GITHUB_WORKSPACE
          make build-nocheck

      - name: Package Installer (MSI)
        shell: cmd
        run: |
          cd instdir
          "C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe" installer.wxs
          "C:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe" installer.wixobj -o TellesoftOffice.msi

      - name: Upload build directory
        uses: actions/upload-artifact@v4
        with:
          name: build-directory
          path: instdir

      - name: Upload MSI installer
        uses: actions/upload-artifact@v4
        with:
          name: TellesoftOfficeInstaller
          path: instdir/TellesoftOffice.msi
