name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install prerequisites with Chocolatey
        run: |
          choco install make nasm ccache --no-progress -y

      - name: Prepare build environment
        run: echo --disable-firebird-sdbc >> autogen.input

      - name: Set up Visual Studio environment
        run: |
          call "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

      - name: Configure LibreOffice
        run: |
          ./autogen.sh --disable-firebird-sdbc --enable-release-build --with-lang=en-US --without-help --without-myspell-dicts --disable-avmedia --with-parallelism=4 --enable-gtk3 --with-vendor="Tellesoft" --with-product-name="Tellesoft Office Professional" || (type config.log && exit 1)

      - name: Build LibreOffice
        run: make

      - name: Package MSI installer
        run: |
          dir instdir
          dir workdir
          echo "Packaging step here"

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: tellesuite-installer
          path: instdir

