name: build-windows

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install prerequisites
      shell: pwsh
      run: |
        choco install -y ninja
        choco install -y ccache

    - name: Set up autogen.input
      run: |
        echo --with-parallelism=4 > autogen.input
        echo --disable-firebird-sdbc >> autogen.input
        echo --disable-pdfium >> autogen.input

    - name: Bootstrap build
      shell: cmd
      run: |
        call winenv.bat
        python3 ./autogen.py

    - name: Build
      shell: cmd
      run: |
        call winenv.bat
        make

    - name: Package MSI installer
      shell: cmd
      run: |
        call winenv.bat
        make MSI

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: tellesoffice-windows-installer
        path: instdir/*.msi
