name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install prerequisites with Chocolatey
        run: |
          choco install -y make
          choco install -y winflexbison3
          choco install -y ccache
          choco install -y 7zip
          choco install -y zip

      - name: Prepare build environment
        run: echo --disable-firebird-sdbc >> autogen.input

      - name: Set up Visual Studio environment
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          echo VS environment initialized.

      - name: Configure LibreOffice
        shell: bash
        run: ./autogen.sh --with-parallelism=2 --disable-firebird-sdbc

      - name: Build LibreOffice
        shell: bash
        run: make

      - name: Package MSI installer
        shell: bash
        run: make package

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: Tellesoft-Office-Windows
          path: instdir/install/en-US/*.msi
